name: AI Security Review

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "**/*.js"
      - "**/*.java"
      - "**/*.php"

jobs:
  ai-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Run AI Security Analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # default Actions token
      run: |
        python scripts/ai_security_scan.py
