name: Auto Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install bump2version
        run: pip install bump2version
      - name: Configure git user
        run: |
          git config --global user.name "Raja Muhammad Awais"
          git config --global user.email "muhammadawaisturk1@gmail.com"
      - name: Bump patch version
        run: bump2version patch
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push --follow-tags origin main
